local sg = Instance.new("ScreenGui")
sg.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
local f = Instance.new("Frame")
f.Size = UDim2.new(0,200,0,100)
f.Position = UDim2.new(0.5,-100,0.5,-50)
f.BackgroundColor3 = Color3.fromRGB(255,0,0)
f.Parent = sg
local t = Instance.new("TextLabel")
t.Size = UDim2.new(1,0,1,0)
t.BackgroundTransparency = 1
t.Text = "TEST OK"
t.TextSize = 20
t.TextColor3 = Color3.new(1,1,1)
t.Parent = f